# Generated by Django 4.0.5 on 2022-06-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('this_season_id', models.IntegerField()),
                ('current_value', models.IntegerField()),
                ('expected_points', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('injury_states', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('this_season_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_scored', models.IntegerField()),
                ('now_injury_status', models.IntegerField()),
                ('season', models.IntegerField()),
                ('gameweek', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.player')),
                ('team_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_against', to='predictor.team')),
                ('team_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_for', to='predictor.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.team'),
        ),
    ]
