# Generated by Django 4.0.5 on 2022-06-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_rename_team_name_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='strength_attack',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='strength_defence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
