# Generated by Django 4.0.5 on 2023-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_team_strength_attack_team_strength_defence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerfixture',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('STR', 'Striker')], max_length=50),
        ),
    ]
